### ISSUE TITLE
Clean up art dataset

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/heartofthevalley#41]
- Add a category for: sponsorship, artist(s) website, source, and production team (if these tags exist. They may not exist for the City of San Jose public art collection). 
- Remove all html tags from the art.js file
- Move html tags into the main.js functions

**Comment by aeevrubin** [comment]
Status: Created a jupyter notebook and have done the following:

1. Flattened the consolidated-artworks.json nests into pandas dataframes tables so they can be easily read and edited as tables. The 'property' table is the one that contains the data to be edited.
2. Fixed typo herf->href which was needed to read html tags with BeautifulSoup
3. From the 'artist' property: stripped the artist names to keep in 'artist' and URLs to merge into the 'website' property.
4. From the 'description' property: stripped the text before 'Source' string to keep in 'description' and stripped URLs to put into 'AdditionalURL' if not already in 'website' or 'sourceURL'
5. Created a loop to output 1st 2 google results for the artist name to  find artists' personal websites(or wikipedia if dead/famous) to merge into 'website' property
6. CURRENTLY: Manually checking those google results and cleaning up any messed up text that I failed to fix with the code.

My cleaning code is available here if anyone wants to check it out: https://github.com/aeevrubin/art_json_cleanup/blob/master/HeartOfValleyEda.ipynb
