### ISSUE TITLE
Ripple Effect and Run River Run is mislocated on the map

### ISSUE THREAD

**Issue by Kyle-Falconer** [codeforsanjose/heartofthevalley#76]
The URL for this is:
https://www.codeforsanjose.com/heartofthevalley/#listing-art_b960b1e410b14a2e4ad4b9353ee3bcdac8298ff1f366b2572c7855352913ab27

The source for this is:
http://sanjoseca.gov/facilities/facility/details/Public-Art-Ripple-Effect-and-Run-River-R-448

![Screen Shot 2019-05-15 at 11 29 11 AM](https://user-images.githubusercontent.com/1034255/57799787-b3b3f280-7704-11e9-9fab-2c46c5ee2dac.png)

Need to create an override for this item so that the marker is in the correct place (or close to it) on the map.

**Comment by ychoy** [comment]
Fixed by #77
