### ISSUE TITLE
Add murals from 2017 POW! WOW! San Jose

### ISSUE THREAD

**Issue by jmlangston** [codeforsanjose/heartofthevalley#79]
Add murals from the 2017 POW! WOW! San Jose to Heart of the Valley. To do this, add the information to `artworks-overrides.json`, and update `consolidated-artworks.json` and `art.js` accordingly. 

Mural information is here: https://www.powwowsanjose.com/ 

This issue follows up the issue 70, adding murals from 2018 POW! WOW!

**Comment by ychoy** [comment]
I'm not sure what happened, because originally, the data was there. 

I noticed that the map is missing some information:
- sources of information from the city public art and murals
- previous data I had added, including the 2017 murals, is now removed from the map
