### ISSUE TITLE
Fix scrapper

### ISSUE THREAD

**Issue by nohjlau** [codeforsanjose/heartofthevalley#84]
SJ government has updated their website and that consequently breaks our scrapper.

![image](https://user-images.githubusercontent.com/52471958/70772202-ab6a7700-1d28-11ea-8631-db73da0e880a.png)

I've been looking at their website and it appears that the URL has changed to here: https://www.sanjoseca.gov/your-government/departments/office-of-cultural-affairs/public-art/collections

In order to prevent future interruptions, we should look to mirror a local copy (or at least a compressed copy).

**Comment by giftofgrub** [comment]
Hi, I can try to tackle this one

**Comment by nohjlau** [comment]
Updated scrapper is looking good! I'm closing this.
