### ISSUE TITLE
Pop up descriptions cutoff

### ISSUE THREAD

**Issue by nohjlau** [codeforsanjose/heartofthevalley#85]
Currently, when there is a popup with an extended description the text will be cut-off at the bottom of the screen. One solution to this is to truncate the description after X number of characters and then have a "Read More" link. There are a number of options with what the "Read More" link would do. One option is to flash the active entry on the sidebar to indicate to the user that is where they should look. Another option is to create a specialized popup that will display all of the content without being cut-off.

![image](https://user-images.githubusercontent.com/52471958/70772519-a1954380-1d29-11ea-9d38-30a02be429bd.png)

**Comment by giftofgrub** [comment]
I'll work on this

**Comment by nohjlau** [comment]
Nice, I already spoke to you on Slack, but let me know if you any questions.

**Comment by nohjlau** [comment]
Your code was merged and the results are looking good! I'm closing this issue.
