### ISSUE TITLE
Adjust center of map to reveal details about an artwork

### ISSUE THREAD

**Issue by giftofgrub** [codeforsanjose/heartofthevalley#91]
![image](https://user-images.githubusercontent.com/49578197/72647259-f92c5d80-392c-11ea-9664-6f8fce672e43.png)
When clicking an artwork, map is centered on the Y-axis, not leaving enough space to show the details. The center needs to be moved down a little so that details can be immediately seen.

**Comment by giftofgrub** [comment]
![image](https://user-images.githubusercontent.com/49578197/72647404-5d4f2180-392d-11ea-87d8-9e6345c075af.png)
After clicking "Read More" details are not seen.

**Comment by nohjlau** [comment]
![fixed nagivation](https://user-images.githubusercontent.com/52471958/72752398-f0c76300-3b76-11ea-8946-6ca1ad886e91.gif)

Nice, thanks for noticing the error. I've made it so we will center based off the size of the popup when we click Read More and revert back to centering on the center of the screen when the Read Less is clicked.
